#!/bin/bash
#open app project
#< xx $1 $2 >
#[code idea | (x-app)]

set +e

case $1 in

  code)
    code $2 ||
    code .
  ;;

  idea)
    test -f $2.iml && open -a 'IntelliJ Idea' $2.iml ||
    test -f $2/$2.iml && open -a 'IntelliJ Idea' $2/$2.iml ||
    test -f pom.xml && open -a 'IntelliJ Idea' pom.xml ||
    test -f $2/pom.xml && open -a 'IntelliJ Idea' $2/pom.xml
  ;;

  *)
    echo -e '[ xx <app> <project> ]'
  ;;

esac

