#!/bin/bash
#remove browser caches
#< xx $1 >
#[ du rm ]

set +e

dir='/Users/dm/Library/Caches'

bra='com.brave.Browser/Cache.db'
chr='com.apple.Chrom/Cache.db'
edg='com.apple.Edge/Cache.db'
fir='com.apple.Firefox/Cache.db'
moz='com.apple.Mozilla/Cache.db'
ope='com.apple.Opera/Cache.db'
saf='com.apple.Safari/Cache.db'

declare -a list=($bra $chr $edg $fir $moz $ope $saf)

case $1 in 

  du)
    for x in ${list[@]}
      do
        test -f $dir/$x && du -h $dir/$x
      done
  ;;

  rm)
    for x in ${list[@]}
      do
        test -f $dir/$x && rm $dir/$x
      done
  ;;

  *)
  ;;

esac
